val fileRdd = sc.textFile("twitter.edges")
val splitRdd = fileRdd.flatMap(line => line.split(" "))
val finalRdd = splitRdd.filter(line => !line.contains(":"))
val words = finalRdd.flatMap(line => line.split(","))
val word1s = words.map(word => (word,1))
val wordCounts = word1s.reduceByKey((a,b) => a+b)
val largerThanOneThousand = wordCounts.filter(x => x._2 > 1000)
largerThanOneThousand.saveAsTextFile("output")
System.exit(0)
